var Message =
    {
        SaveSucessful: "保存数据成功!!",
        SaveFailed: "保存数据失败!!",

        OrganIdNull: "机构号不能为空",
        OrganNameNull: "机构名称不能为空",
        OrganBriefNameNull: "机构简称不能为空",
        StatusNotSelected: "没有选择状态",
        FrontVersionNotSelected: "没有选择前端版本",
        OrganTypeNotSelected: "没有选择机构类型",
        AddressNull: "地址不能为空",
        PhoneNull: "电话不能为空",
        MobileNull: "手机号码不能为空",
        MobileInValid: "手机号码无效",
        EmailNull: "Email不能为空",
        EmailInvalid: "Email无效",
        ContactPeopleNull: "联系人不能为空",
        OpenBankNameNull: "开户行名称不能为空",
        OpenBankIdNull: "开户行行号不能为空",
        AccountNameNull: "账户名不能为空",
        AccountIdNull: "账户号不能为空",
        TaxIdNull: "税号不能为空",
        ProfitXNull: "分润设置X不能为空",
        ProfitYNull: "分润设置Y不能为空",
        PeopleNameLimit: "人名长度不能超过5",
        PhoneError: "电话号码不正确",
        AreaNotSelected: "没有选择区域",
        OrganChannelNameNull: "渠道名称不能为空",
        OrganChannelTypeNotSelected: "没有选择渠道类型",
        NeedAuditNotSelected: "没有选择是否审核",
        NeedSecondAutidNotSelected: "没有选择是否二级审核",

        VendorNameNull: "商户名称不能为空",
        VendorEnglishNameNull: "商户英文名称不能为空",
        VendorBriefNameNull: "商户简称不能为空",
        ParentVendorSysNoNull: "上级商户不能为空",
        VendorCategoryNotSelected: "没有选择行业类别",
        ExpandOrganNull:"拓展机构不能为空",
        IsStoreNotSelected: "没有选择是否终端门店",
        WeixinPublicIdNull: "微信公众号不能为空",
        LongitudeNull: "经度不能为空",
        LongitudeNotDecimal: "经度只能是数字",
        LatitudeNull: "纬度不能为空",
        LatitudeNotDecimal: "纬度只能为数字",
        CorporationCertificateNull: "企业法人证件不能为空",
        TaxRegCertificateNull: "税务登记证不能为空",
        OrganizationCodeNull: "组织机构代码不能为空",
        BizLicenseIdNull: "营业执照号不能为空",
        OpenAccountPermitNull: "开户许可证不能为空",
        CoopAgreementCertificateNull: "合作协议证不能为空",
        VendorAppNull: "至少选择开通一个应用",
        VendorSaleChannelNull: "至少选择一个销售渠道",
        ExistSameWeixinBizType: "不能存在相同的业务类型",
        WeixinBizTypeNotSelected: "没有选择微信业务类型",
        WeixinBizTitleNull: "微信标题不能为空",
        AvgPriceNull: "均价不能为空",
        OnlyDecicaml: "只能为小数",
        MCCCodeNull: "MCC码不能为空",
        BranchCodeNull: "POS管理机构不能为空",
        ExpressTypeNotSelected:"没有选择任何快递方式",

        SettlementTypeNotSelected: "没有选择佣金结算方式",
        SettlementPeriodUnitNotSelected: "没有选择结算周期",
        BalanceTypeNotSelected: "没有选择结算方式",
        BalanceTimeNull: "结算时间不能为空",
        BalanceTimeInteger: "结算时间只能为整数",
        AccountOpenedBankNameNull: "开户行名称不能为空",
        AccountOpenedBankIdNull: "开户行行号不能为空",
        AccountNameNull: "账户名不能为空",
        AccountNull:"账号不能为空",
        TaxIdNull: "税号不能为空",
        CommCalcTypeNotSelected: "没有选择计费方式",
        CommCalcXNull: "计费设置X不能为空",
        CommCalcYNull: "计费设置Y不能为空",

        ParentOrganNull: "上层机构不能为空",
        OrganLevelNotSelected: "没有选择机构层级",

        ExpressNameNull: "快递名不能为空",
        DisplayNameNull: "快递显示名不能为空",
        PriceNull: "同城价格不能为空",
        DistancePriceNull: "异地价格不能为空",
        OrganBelongedNull: "所属机构不能为空",

        OperatorNameNull: "操作员名称不能为空",
        RolseNotSelected: "没有选择角色",

        SameProductCategorySelected: "同一级不能存在相同的商品种类",
        ProductCategoryNotSelected:"没有选择商品类别"
    };